### ISSUE TITLE
[Question] Why do we clone a thread instead of using next_ref.thread.unpark?

### ISSUE THREAD

**Issue by SirCollypso** [kaist-cp/cs431#919] opened 2024-04-12 13:47 UTC
![Screenshot_20240412_224343](https://github.com/kaist-cp/cs431/assets/26387525/1cf65902-85ae-48ac-846c-10b5c044e8e3)

Why do we need to clone a thread instead of using next_ref.thread.unpark()? I understand the ordering issue and that we need to store before unparking. But why cannot we use next_ref.thread after store?

**Comment by m-spitfire** [comment] 2024-04-12 14:41
Duplicate of #176

**Closed** 2024-04-12 14:42 UTC
Labels: question
