### ISSUE TITLE
[Question] How do I run scripts in the homework/scripts folder?

### ISSUE THREAD

**Issue by SansyHuman** [kaist-cp/cs431#615] opened 2022-08-31 13:30 UTC
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

(YOUR QUESTION HERE)
How do I run scripts in homework/scripts folder? I first tried to run them on Windows 11, but it showed the error message "bash: zip: command not found". So next I tried to run it on WSL Ubuntu 20.04.3 LTS, but it showed the error message "/usr/bin/env: 'bash\r': No such file or directory".
I cannot run the scripts. How can I fix this?

![image](https://user-images.githubusercontent.com/29447695/187689506-89940574-04f0-4d29-89b7-514cdfb609c6.png)
![image](https://user-images.githubusercontent.com/29447695/187689955-b4a790f7-7cb9-44fe-8517-fd2ca6a27070.png)

**Comment by drash99** [comment] 2022-08-31 13:33
I think it is caused by windows CRLF line finishing.
Try git pull in linux directly.

**Comment by Lee-Janggun** [comment] 2022-08-31 13:57
Since we use features of [nightly rust](https://doc.rust-lang.org/book/appendix-07-nightly-rust.html), it is quite difficult to maintain this repo for different architectures/OSs, so we only maintain this repo to work on Linux. 

If the method in the above approach does not work, please try it on the server we provided.

**Comment by jeehoonkang** [comment] 2022-09-02 06:02
And please don't paste error messages with an image. Please use

```rust
fn code_blocks() {
    println!("like this.");
}
```

**Comment by jeehoonkang** [comment] 2022-09-02 06:02
Closing due to the use of images, FYI.

**Closed by jeehoonkang** 2022-09-02 06:02 UTC
Labels: question
